name: remote ssh command
on:
  #schedule:
  #  - cron: '0 * * * *'
  workflow_dispatch: 


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 192.168.202.19
          username: root
          password: QwertY_13
          proxy_host: ${{ secrets.JUMP_IP }}
          proxy_port: ${{ secrets.JUMP_PORT }}
          proxy_username: jump_sa
          proxy_password: ${{ secrets.JUMP_PW }}
          script: |
            FAILED_PODS=`kubectl get pods -A | awk '$4!="Running" && $4!="Succeeded" { print $2 }' | tail +2`
            echo "$FAILED_PODS" > failed_pods.txt

                    
  
