name: remote ssh command
on:
  #schedule:
  #  - cron: '0 * * * *'
  workflow_dispatch: 


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 192.168.208.19
          username: root
          password: QwertY_13
          proxy_host: ${{ secrets.JUMP_IP }}
          proxy_port: ${{ secrets.JUMP_PORT }}
          proxy_username: jump_sa
          proxy_password: ${{ secrets.JUMP_PW }}
          script: kubectl get pods -A > failed_pods.txt
      
      - name: download
        uses: nicklasfrahm/scp-action@main
        with:
          direction: download
          insecure_ignore_fingerprint: true
          host: 192.168.208.19
          insecure_password: QwertY_13
          username: root
          proxy_host: ${{ secrets.JUMP_IP }}
          proxy_port: ${{ secrets.JUMP_PORT }}
          proxy_username: jump_sa
          insecure_proxy_password: ${{ secrets.JUMP_PW }}
          insecure_proxy_ignore_fingerprint: true
          source: /root/failed_pods.txt
          target: ./failed_pods.txt

      - name: variable
        id: result
        run: |
          CONTENT=$(cat failed_pods.txt)
          # Экранируем специальные символы для GitHub Actions
          #CONTENT="${CONTENT//'%'/'%25'}"
          #CONTENT="${CONTENT//$'\n'/'%0A'}"
          #CONTENT="${CONTENT//$'\r'/'%0D'}"
          echo "file_content=$CONTENT" >> $GITHUB_OUTPUT
                
      
      - name: Report to Slack
        #if: steps.result.outputs.FAILED_PODS != ''
           
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: general
          SLACK_COLOR: failure
          SLACK_MESSAGE: "List of fallen pods: ${{ steps.result.outputs.file_content }}"
          SLACK_TITLE: Some pods have failed
          SLACK_USERNAME: xaos613
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        
