name: Setup Minikube Cluster

on:
  push

jobs:
  setup-minikube:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Install Minikube
      run: |
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo chmod +x minikube
        sudo mv minikube /usr/local/bin/

    - name: Install kubectl
      run: |
        curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.24.0/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/

    - name: Start Minikube
      run: |
        minikube start --driver=docker --insecure-registry="localhost:5000"

    - name: Wait for Minikube to be ready
      run: |
        kubectl wait --for=condition=Ready pod --all --namespace=kube-system --timeout=60s

    - name: Run tests
      run: |
          kubectl cluster-info --context minikube
          kubectl version
          kubectl get pods -n minikube
          kubectl get nodes
        # Add your specific tests here, such as deploying services, running tests, etc.
